"use client";
import BottomNavigation from "@/components/BottomNavigation";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { usePage } from "@/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Windows 11 Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const page = usePage((state) => state.onWhichPage);

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${page === "desktop" ? "bg-bgDesktopImage" : "bg-bgLockScreenImage"}  h-screen flex flex-col w-full`}
      >
        {children}

        {page === "desktop" && <BottomNavigation />}
      </body>
    </html>
  );
}
